### ISSUE TITLE
Bouding box on predicted fruit

### ISSUE THREAD

**Issue by AnhHC** [Horea94/Fruit-Images-Dataset#10]
Hello Horea, 

Can you help me on drawing a boundingbox for detected fruit ?

Thanks

**Comment by Horea94** [comment]
In order to draw a bounding box on a detected fruit from an image, you would need a program that locates regions of interest(in this case regions with fruits) in the image and then identifies the class of the fruit using a classifier.
In this repository we have only the classifier so far. We have plans to add code to identify the regions of interest in the future but we cannot estimate yet when it will be available.
