### ISSUE TITLE
training file

### ISSUE THREAD

**Issue by mohammad69h94** [Horea94/Fruit-Images-Dataset#11]
hi . good evening.
I do not have a powerful system to training. It is possible for you to give me the trained files.
Thanks so much.
M.Hamidi
mohammad69h94@gmail.com

**Comment by Arnold0210** [comment]
Hi, good morning, 
the original dataset I got from:
 https://github.com/Horea94/Fruit-Images-Dataset, https://www.kaggle.com/moltean/fruits 
in this link you can find all files include the training and test files.

Enviado desde Correo para Windows 10
 Arnold Julian Herrera Quiñones
Student of System Engineering 
Catholic University of Colombía
Consultant on Periferia IT Group

De: mohammad69h94
Enviado: lunes, 31 de diciembre de 2018 3:22 a. m.
Para: Horea94/Fruit-Images-Dataset
CC: Subscribed
Asunto: [Horea94/Fruit-Images-Dataset] training file (#11)

hi . good evening.
I do not have a powerful system to training. It is possible for you to give me the trained files.
Thanks so much.
M.Hamidi
mohammad69h94@gmail.com
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus

-- 
*AVISO LEGAL: 
- Las opiniones que contenga este mensaje son de su autor y 
no necesariamente representan la opinión oficial de la Universidad Católica 
de Colombia o de su directiva.
- El receptor deberá verificar posibles 
virus informáticos que tenga el correo o cualquier anexo a él, razón por la 
cual la Universidad Católica de Colombia no aceptará responsabilidad alguna 
por daños causados por cualquier virus transmitido en este correo.
- La 
información contenida en este mensaje y en los archivos electrónicos 
adjuntos es confidencial y reservada, conforme a lo previsto en la 
Constitución y en la Ley 1273 del 5 de Enero de 2009, y está dirigida 
exclusivamente a su destinatario, sin la intención de que sea revelada o 
divulgada a otras personas. El acceso al contenido de esta comunicación por 
cualquier otra persona diferente al destinatario no está autorizado por 
*l*a Universidad Católica de Colombia y está sancionado de acuerdo con las 
normas legales aplicables.
- El que ilícitamente sustraiga, oculte, 
extravíe, destruya, intercepte, controle o impida esta comunicación, antes 
de que llegue a su destinatario, estará sujeto a las sanciones penales 
correspondientes. Igualmente, incurrirá en sanciones penales el que, en 
provecho propio o ajeno o con perjuicio de otro, divulgue o emplee la 
información contenida en esta comunicación. En particular, los servidores 
de Internet públicos que reciban este mensaje están obligados a asegurar y 
mantener la confidencialidad de la información en él contenida y, en 
general, a cumplir con los deberes de custodia, cuidado, manejo y demás 
previstos en el régimen disciplinario.
- Si por error recibe este mensaje, 
le solicitamos enviarlo de vuelta a la Universidad Católica de Colombia, a 
la dirección de correo electrónico que se lo envió, y borrarlo de sus 
archivos electrónicos o destruirlo.

LEGAL NOTICE:
- Any opinions contained 
in this message are exclusive of its author and not necessarily represent 
the official position of "Universidad Catolica de Colombia" or of its 
authorities.
- The recipient must verify the presence of possible 
informatic viruses in the mail or in any annex thereto, and for this reason 
"Universidad Catolica de Colombia" shall not be made liable for any damages 
caused by viruses transmitted hereby.
- The information contained in this 
message and in any electronic files annexed thereto is confidential and 
privileged, as per the Colombian Constitution and the Law that governs 
"Universidad Catolica de Colombia" and is directed exclusively to its 
addressee, with no intention of it being disclosed or revealed to third 
parties. The access to the content of this communication by any person 
different from its addressee is not authorized by "Universidad Catolica de 
Colombia" and shall be penalized in accordance with the applicable legal 
dispositions.
- Any person who illicitly removes, hides, distracts, 
destroys, intercepts, controls, or otherwise prevents this communication 
from arriving to its addressee, shall be subject to the appropriate 
criminal penalties. Likewise, criminal penalties shall be incurred by any 
who, either for his/her own benefit or on behalf of third parties, or with 
prejudice of a third party, discloses or employs the information contained 
in this communication. In particular, public servants that may receive this 
message shall be obliged to ensure and keep the confidentiality of the 
information contained therein and, in general, to comply with the duties of 
custody, care, handling and other provided under the disciplinary regime.
- 
If you should happen to receive this message by mistake, please send it 
back to "Universidad Catolica de Colombia" to the same e-mail address and 
either delete it from your electronic files or destroy it.*
