### ISSUE TITLE
Checkpoint error when freezing

### ISSUE THREAD

**Issue by BartuHTC** [Horea94/Fruit-Images-Dataset#16]
When I run freeze_graph.py with the following flags;
>python freeze_graph.py --input_checkpoint=C:\Tensorflow1\object_detection\fruit_models\checkpoint --output_graph=C:\Tensorflow1\object_detection\fruit_models\frozen_graph.pb --output_node_names = C:\Tensorflow1\object_detection\fruit_models\out\out --input_meta_graph_def = C:\Tensorflow1\object_detection\fruit_models\model.ckpt.meta

I encounter the following error:
  File "C:\Users\...\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file C:\Tensorflow1\object_detection\fruit_models\checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

Do you have any idea how to fix this?
Thanks in advance.

**Comment by Horea94** [comment]
This issue might appear because the version of TensorFlow used for this project is slightly old at this point. The file freeze_graph.py is provided with every version of TensorFlow so a potential fix is to try a different version of the script. You can find the latest version here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py
